### ISSUE TITLE
Failto fetch dicom3tools_1.00.snapshot.20151213160232.tar.bz2

### ISSUE THREAD

**Issue by rafaftahsin** [welcheb/docker_dicom_tools#1]
while building docker image got the following error

`The command '/bin/sh -c wget http://www.dclunie.com/dicom3tools/workinprogress/dicom3tools_1.00.snapshot.20151213160232.tar.bz2' returned a non-zero code: 8`

**Comment by ojosephs** [comment]
NB. Not solved. The following two lines are still referring to the old link.

Suggest::
RUN wget http://www.dclunie.com/dicom3tools/workinprogress/dicom3tools_1.00.snapshot.20160721064406.tar.bz2
RUN tar xvjf dicom3tools_1.00.snapshot.20160721064406.tar.bz2
WORKDIR "/dicom3tools_1.00.snapshot.20160721064406"

**Comment by welcheb** [comment]
Thank you. The corrections are now committed.
